# Generated by Django 3.0.2 on 2020-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(default='', upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
