# Generated by Django 3.0.2 on 2020-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(default='imagenes/no_image.png', upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
