# Generated by Django 3.0.2 on 2020-02-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privado',
            field=models.BooleanField(default=False, verbose_name='Privado'),
        ),
    ]
