# Generated by Django 3.0.2 on 2020-02-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Comentario', verbose_name='Respuesta'),
        ),
    ]
